langauge: ruby
rbenv:
- 2.5.3
#- addons:
#    postgresql: 9.6
#    chrome: stable
#  dist: xenial
#  before_install:
##    - yes | gem update --system --force
#    - gem install bundler
#- script:
#    - yarn
#    - bundle exec rails db:{create,migrate} RAILS_ENV=test
#    - bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: fPl16DzFXtERITMqz2uINoJOca8tYN+fh71yM93oepYEWDOB0QUV4VM9AsVRBqvuZEcTWqFZdb8+9tVdYG1e1s6EQJdRjfDN9aKNnsu+4ng/3eLtBwGtvxHMlxJah9q+yJHogTZgt3sJBIqOVNmj2ieowCUvq9H4k1xeHMGeeau27aJEgFihLXaHXRoIkng9U02QvPD9+ufhUp7C1pC4RNgjW0iCwINlZCy4oazFGl/5gRhsgEhcnLj7zIW+vn1pWAa8cFvK7RrZrXwi/qZD1kDsejelAtKSlcUSmgqhXzYQaL9n2+0OOitMrqd6zBBH7U5ZYrI+rrOg/Sdk4ycxHJh2hE8kk+1ifkf92UR3OrKqIDCQk5+KDKuR0TRwwKUn0CW6Rp3a/LZDtCBrsHepVIdroHwAOCjqxWPbWYcTBSHnuqoWL1Q2Ph8mugYTn9cT4HMVGQlgaQXKUzqD+zzvL3Nq7+2jkxh4WCp1vMNZLENiiBY1IIpNo1Ibo3XXscFqqRFVDXKedcBZMnRL7xAmmTLM53koAW99iB0wdi6Kx7PYB/y+PxtYUZSTYIshvajQs3yA8qvqUMnKl6qlHOfa462aixEZR51VM1jMAZxzLvE/4i2nmsMLH/UiR2E5S1A0V5rpNiW+Sxyar9chIu/6QImpPyDELhJ+xJVBm1Qqs60=
  app: hidden-inlet-79770
  skip_cleanup: true
